### ISSUE TITLE
Not needed with Bundler 1.11.2

### ISSUE THREAD

**Issue by schneems** [timolehto/heroku-bundle-config#4]
With Bundler 1.11.2 you can set all the values you might want in your environment variables https://devcenter.heroku.com/articles/bundler-configuration.

This buildpack breaks people's builds with the new bundler since it caches the .bundle/config between builds which can include absolute paths even though the path changes on every build. Recently the Ruby buildpack switch to not caching the bundler config, here is the changelog https://devcenter.heroku.com/changelog-items/854

Here is the relevant pr: https://github.com/heroku/heroku-buildpack-ruby/pull/471

Can you update master to not use the cache?

**Comment by timolehto** [comment]
Thanks for the info, sorry for the slow reaction. I've addressed the issue with this:
https://github.com/timolehto/heroku-bundle-config/pull/5
